x-common-settings: &common-settings
  build:
    context: .
    dockerfile: .dockerfiles/Dockerfile
  depends_on:
    db:
      condition: service_healthy
  env_file:
    - ".env"
  init: true
  volumes:
    - ./media_root:/src/media_root
    - ./static_root:/src/static_root
    - .:/src
    - django-tailwind-cli-data:/src/.django_tailwind_cli

services:

  db:
    image: "pgautoupgrade/pgautoupgrade:17-alpine"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - .:/src
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  hawkhundred:
    <<: *common-settings
    command: ["uv", "run", "-m", "manage", "runserver", "0.0.0.0:8000"]
    entrypoint: ["/src/compose-entrypoint.sh"]
    environment:
      - "DJANGO_SETTINGS_MODULE=config.settings_hawkhundred"
    ports:
      - 8010:8000
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck-web.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  tailwind:
    <<: *common-settings
    command: ["uv", "run", "-m", "manage", "tailwind", "watch"]

  web:
    <<: *common-settings
    command: ["uv", "run", "-m", "manage", "runserver", "0.0.0.0:8000"]
    entrypoint: ["/src/compose-entrypoint.sh"]
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "./healthcheck-web.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # qcluster:
  #   <<: *common-settings
  #   # command: ["python", "manage.py", "qcluster"]
  #   command: ["python", "-m", "manage", "qcluster", "--skip-checks"]

volumes:
  django-tailwind-cli-data:
  postgres-data:
